### ISSUE TITLE
Help with Markbot Errors

### ISSUE THREAD

**Issue by breecousineau** [breecousineau/use-all-the-selectors#1]
Hi @wendywarren

I was wondering if you would be able to look over my code. I can't seem to find the issue of what isn't working

Kindly,

Bree

<img width="792" alt="Screen Shot 2022-03-11 at 11 16 11 AM" src="https://user-images.githubusercontent.com/97452245/157905863-5084baab-059a-4049-b5cf-0cc7eb0bfc28.png">

**Comment by wendywarren** [comment]
Hi @breecousineau,

I noticed a few things that should help bring you to a state where you can submit.

For the html in your css, you didn't have to include the background-color, font-family or line-height. In class I did say that those properties are ones you should include when creating your projects but apparently Markbot did not like students including anything other than border-box. I will clarify that next class but for now all Markbot wants to see is:

```
html {
  box-sizing: border-box;
}
```

#2 - It is asking for you to select the header and footer. In that case we would simply just add a comma in between both elements as you did with selecting the ids in #6. 

```
header,
footer {
  font-size: 1.5rem;
}
```

#3 - To select the ul inside nav you would list one element after another. Since ul is nested inside of nav you would use a descendent selector. Similar to the child one you chose but a descendent is displayed like this:

```
nav ul {
  font-family: sans-serif;
}
```

#11 and #12 - For first and last child selectors you want to first start with the parent element and then target the child element like this:

```
ol li:first-child {
  color: #719e47;
}

ol li:last-child {
  color: #2aa198;
}
```

#13, 14, 15 - You were on the right track with nth child but just ordered them incorrectly. This is how you would want to select it in css:

```
.types li:nth-child(odd) {
  background-color: #657ba3;
}
```

It looks like you get it though. Just a few corrections to make and you're good to go. Takes time to become comfortable with selectors.

Let me know if you have any questions. We'll go over the exercise in class too.

Wendy

**Comment by breecousineau** [comment]
Hi @wendywarren 

Thank you very much for these explanations! I think I am understanding it a bit more now

Thank you and see you in person tomorrow :)

Bree
